CREATE TABLE orders (
  id SERIAL PRIMARY KEY,
  order_id VARCHAR(255) UNIQUE NOT NULL,
  date DATE NOT NULL,
  address TEXT NOT NULL,
  status1 BOOLEAN DEFAULT FALSE,
  status2 BOOLEAN DEFAULT FALSE,
  status3 BOOLEAN DEFAULT FALSE,
  log TEXT DEFAULT ''
);
